"""exp_14: publish one arm's ten cells into the checkout that owns ``model_comparison.md``.

Announcement 04 wants the cross-experiment table updated per arm, immediately -- and the
table is regenerated by globbing raw per-seed metric JSONs *inside* the FLAC checkout on
branch ``localization-exp``. exp_14's cells are written to the NAS instead, so publishing
an arm means copying ten files across and registering a glob for them. Every step of that
fails quietly, which is what this module is for:

* **The glob decides which validator runs.** ``gen_model_comparison.py::is_exp14_row``
  claims any row whose pattern contains ``exp14_`` for the exp_14 *yaw* campaign, with a
  different protocol label and a validator that cannot parse these eval names (finding
  r3-3). Nothing this module emits -- directory, basename, label or pattern -- may carry
  that substring, and ``names.assert_no_forbidden_substring`` is applied to each.
* **A metrics JSON cannot prove it is this cell.** It records no seed and no dataset
  config, so a file left over from an earlier checkpoint, an earlier protocol or a reduced
  eval split reads as a finished result. The import therefore gates on the *pair*: the
  metrics record (checkpoint path, the digest the evaluator stamped in, all four
  conditioning flags) and its sibling prediction bundle (full 6,337-item split, the
  K-appropriate unseen config, same seed, same protocol, exactly-as-scored tensor).
* **A half-published arm is averaged without complaint.** So validation runs over all ten
  cells before a single byte is copied, the copy lands in a staging directory whose files
  are re-hashed before they are moved into place, and every digest is recorded beside the
  source path it came from in ``MANIFEST.sha256``.

No GPU, no network, and nothing in the destination checkout is committed or force-added
here: this module copies and prints, the analyst commits.
"""
import argparse
import glob
import hashlib
import os
import shutil
import sys

from src.tools.data_curve import names

#: Inside the FLAC checkout, relative to its root. Deliberately not ``exp14_*``.
IMPORT_SUBDIR = os.path.join("outputs_FLAC", "data_curve_import")
#: What gen_model_comparison.py calls each arm's evaluation protocol. Mirrors the labels
#: already in its ROWS table ("fa eval" for frame-averaged arms, "vanilla eval" for stock),
#: so an exp_14 row reads in the same vocabulary as every row beside it.
ARM_PROTOCOL_LABEL = {"cyl": "fa eval", "van": "vanilla eval"}
MANIFEST_BASENAME = "MANIFEST.sha256"
EXIT_OK = names.EXIT_OK
EXIT_INPUT_ERROR = names.EXIT_INPUT_ERROR
EXIT_REFUSED = names.EXIT_BUNDLE_VIOLATION


def seed_glob(seeds=names.SEEDS):
    """``s4[2-6]`` for seeds 42-46 -- derived, with a guard, never typed."""
    low, high = min(seeds), max(seeds)
    if sorted(seeds) != list(range(low, high + 1)) or low // 10 != high // 10:
        raise ValueError(f"seeds {sorted(seeds)} are not one contiguous decade, so a "
                         "single character-class glob cannot name exactly them")
    return f"s{low // 10}[{low % 10}-{high % 10}]"


def row_spec(arm, tag, K, run=None, seeds=names.SEEDS):
    """The line to paste into ``gen_model_comparison.py``'s ROWS table for one cell block.

    ``(label, protocol, K, [glob])`` -- the four-field form every row there uses. The glob
    is relative to the FLAC checkout's root, which is what the generator resolves against.
    ``names.run_id`` does the arm/tag validation, so an unknown arm cannot reach the label.
    """
    run = run or names.run_id(arm, tag)
    if K not in names.K_VALUES:
        raise ValueError(f"unplanned K={K!r}; the experiment evaluates {names.K_VALUES}")
    pct = int(round(names.FRACTIONS[tag] * 100))
    label = f"data-curve {arm} f={pct}% @40k (exp_14 cyl-dinov3)"
    pattern = f"{IMPORT_SUBDIR}/{run}/*_K{K}_{seed_glob(seeds)}*.json"
    names.assert_no_forbidden_substring(label)
    names.assert_no_forbidden_substring(pattern)
    return f'("{label}", "{ARM_PROTOCOL_LABEL[arm]}", {K}, ["{pattern}"]),'


def _final_checkpoint(run_dir, step=names.MAX_STEPS):
    """The run's single step-``step`` checkpoint, or ``None`` with a reason."""
    hits = sorted(glob.glob(os.path.join(glob.escape(run_dir), f"*step={step}.ckpt")))
    if len(hits) == 1:
        return hits[0], None
    if not hits:
        return None, f"no step-{step} checkpoint in {run_dir}: this arm is not finished"
    return None, (f"{len(hits)} step-{step} checkpoints in {run_dir} -- which one produced "
                  "the cells beside them is not decidable here")


def _sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as fin:
        for chunk in iter(lambda: fin.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_cells(ckpt, arm, tag, expect_ckpt_sha256, seeds=names.SEEDS,
                   ks=names.K_VALUES, expect_n=None):
    """``(files, violations)`` -- every cell of one arm, gated as a metrics/bundle *pair*.

    ``expect_n`` overrides the 6,337-item contract for fixtures only; production callers
    leave it ``None`` so the split size comes from ``names.N_ITEMS_UNSEEN``.
    """
    n_items = names.N_ITEMS_UNSEEN if expect_n is None else expect_n
    cond_method = names.ARM_COND_METHOD[arm]
    files, violations = [], []
    for K in ks:
        for seed in seeds:
            where = f"K{K} s{seed}"
            metrics_path = names.metrics_json_path(ckpt, arm, tag, K, seed)
            bundle_path = names.predictions_pt_path(ckpt, arm, tag, K, seed)
            if not os.path.exists(metrics_path):
                violations.append(f"{where}: no metrics JSON at {metrics_path}")
                continue
            bad = names.check_metrics(metrics_path, ckpt, expect_ckpt_sha256, cond_method,
                                      names.FRAME_AVG_ANGLES, names.ROTATE_DEG,
                                      names.COND_AUTOCAST)
            if not os.path.exists(bundle_path):
                bad.append(f"no prediction bundle at {bundle_path}, so nothing proves this "
                           f"cell covered the full {n_items}-item unseen split")
            else:
                bad += names.check_bundle(bundle_path, n_items, seed, K, arm,
                                          expect_eval_name=names.eval_name(arm, tag, K, seed),
                                          expect_ckpt=ckpt,
                                          expect_ckpt_sha256=expect_ckpt_sha256)
            if bad:
                violations += [f"{where}: {line}" for line in bad]
                continue
            files.append({"source": metrics_path, "K": K, "seed": seed,
                          "sha256": _sha256(metrics_path)})
    return files, violations


def _copy_verified(files, dest_dir):
    """Copy into a staging dir, re-hash every byte, then move into place. Or copy nothing."""
    staging = os.path.join(dest_dir, f".incoming-{os.getpid()}")
    os.makedirs(staging, exist_ok=True)
    violations = []
    try:
        for entry in files:
            basename = names.assert_no_forbidden_substring(os.path.basename(entry["source"]))
            staged = os.path.join(staging, basename)
            shutil.copy2(entry["source"], staged)
            digest = _sha256(staged)
            if digest != entry["sha256"]:
                violations.append(
                    f"{basename}: the copy hashes to {digest}, not the source's "
                    f"{entry['sha256']} -- nothing was imported")
                return violations
            entry["dest"] = os.path.join(dest_dir, basename)
        for entry in files:
            os.replace(os.path.join(staging, os.path.basename(entry["dest"])), entry["dest"])
    finally:
        shutil.rmtree(staging, ignore_errors=True)
    return violations


def _write_manifest(dest_dir, checkout, run, ckpt, ckpt_sha256, files):
    """``MANIFEST.sha256``: the sources above, the imported copies below.

    The lower half is a plain ``sha256sum -c`` list rooted at the FLAC checkout; the upper
    half is commented out (``sha256sum`` skips ``#`` lines) and names the NAS path each
    copy came from, which is the half a reader needs and ``sha256sum`` has no room for.
    """
    path = os.path.join(dest_dir, MANIFEST_BASENAME)
    lines = [f"# exp_14 data-curve import -- {run}",
             "# written by src.tools.data_curve.import_cells (announcement 04, plan §9 D9)",
             f"# final checkpoint:        {ckpt}",
             f"# final checkpoint sha256: {ckpt_sha256}",
             "#", "# --- sources (sha256  NAS path) ---"]
    lines += [f"#{entry['sha256']}  {entry['source']}" for entry in files]
    lines += ["#", "# --- imported copies (sha256  path relative to the FLAC checkout) ---"]
    lines += [f"{entry['sha256']}  {os.path.relpath(entry['dest'], checkout)}"
              for entry in files]
    with open(path, "w") as fout:
        fout.write("\n".join(lines) + "\n")
    return path


def import_run(nas_root, arm, tag, flac_checkout, expect_ckpt_sha256, seeds=names.SEEDS,
               ks=names.K_VALUES, expect_n=None, ckpt=None):
    """Copy one arm's ten metric JSONs into the FLAC checkout, or copy none of them.

    Returns ``(result, violations)``. ``violations`` non-empty means nothing was copied --
    a half-published arm would be globbed and averaged exactly like a complete one.
    ``ValueError`` is raised only for a caller bug (unknown arm/tag, a digest that is not a
    digest): that is not a verdict about the artifacts.
    """
    run = names.run_id(arm, tag)                    # validates the arm and the fraction
    # The one rule about what a checkpoint digest may be lives in names; re-stating it here
    # would create a second definition of "valid digest" that can drift from the launcher's.
    names._check_ckpt_sha256(expect_ckpt_sha256)
    run_dir = os.path.join(nas_root, run)
    dest_dir = os.path.join(flac_checkout, IMPORT_SUBDIR, run)
    names.assert_no_forbidden_substring(os.path.join(IMPORT_SUBDIR, run))
    result = {"run_id": run, "arm": arm, "fraction_tag": tag, "run_dir": run_dir,
              "dest_dir": dest_dir, "ckpt": ckpt, "ckpt_sha256": expect_ckpt_sha256,
              "files": [], "manifest": None,
              "row_specs": [row_spec(arm, tag, K, run) for K in ks]}
    if ckpt is None:
        ckpt, why = _final_checkpoint(run_dir)
        if ckpt is None:
            return result, [f"{run}: {why}"]
        result["ckpt"] = ckpt
    on_disk = _sha256(ckpt) if os.path.exists(ckpt) else None
    if on_disk != expect_ckpt_sha256:
        return result, [f"{run}: {ckpt} hashes to {on_disk}, not the ckpt_sha256 "
                        f"{expect_ckpt_sha256} the launcher validated"]
    files, violations = validate_cells(ckpt, arm, tag, expect_ckpt_sha256, seeds, ks,
                                       expect_n)
    if violations:
        return result, violations
    os.makedirs(dest_dir, exist_ok=True)
    violations = _copy_verified(files, dest_dir)
    if violations:
        return result, violations
    result["files"] = files
    result["manifest"] = _write_manifest(dest_dir, flac_checkout, run, ckpt,
                                         expect_ckpt_sha256, files)
    return result, []


def main(argv=None):
    """CLI: import one arm's cells and print the rows to add to gen_model_comparison.py."""
    parser = argparse.ArgumentParser(
        prog="python -m src.tools.data_curve.import_cells",
        description="Copy one exp_14 arm's ten metric JSONs into the FLAC checkout that "
                    "regenerates model_comparison.md, sha-verified, all-or-nothing.")
    parser.add_argument("--nas-root", required=True,
                        help="the directory holding the dc_<arm>_f<tag> run directories")
    parser.add_argument("--arm", required=True, choices=list(names.ARMS))
    parser.add_argument("--tag", required=True, choices=sorted(names.FRACTIONS))
    parser.add_argument("--flac-checkout", required=True,
                        help="the checkout that owns gen_model_comparison.py "
                             "(branch localization-exp)")
    parser.add_argument("--expect-ckpt-sha256", required=True,
                        help="the launch summary's final_ckpt_sha256 for this arm")
    parser.add_argument("--ckpt-path", default=None,
                        help="override the discovered step-40000 checkpoint (rarely needed)")
    args = parser.parse_args(argv)
    try:
        result, violations = import_run(args.nas_root, args.arm, args.tag,
                                        args.flac_checkout, args.expect_ckpt_sha256,
                                        ckpt=args.ckpt_path)
    except (OSError, ValueError) as err:
        print(f"import_cells: {type(err).__name__}: {err}", file=sys.stderr)
        return EXIT_INPUT_ERROR
    if violations:
        print(f"REFUSED: {result['run_id']} was not imported "
              f"({len(violations)} violations); nothing was copied", file=sys.stderr)
        for line in violations:
            print(f"  ! {line}", file=sys.stderr)
        return EXIT_REFUSED
    print(f"imported {len(result['files'])} cells of {result['run_id']} -> "
          f"{result['dest_dir']}")
    print(f"manifest: {result['manifest']} ({MANIFEST_BASENAME} verified after copy)")
    print("add these rows to worklog/worklog_yixun/gen_model_comparison.py::ROWS, "
          "force-add the JSONs + manifest, regenerate, commit and push:")
    for row in result["row_specs"]:
        print(f" {row}")
    return EXIT_OK


if __name__ == "__main__":     # pragma: no cover - exercised through main() in tests
    sys.exit(main())
