"""exp_14: publish one arm's ten cells into the checkout that owns ``model_comparison.md``.

Announcement 04 wants the cross-experiment table updated per arm, immediately -- and the
table is regenerated by globbing raw per-seed metric JSONs *inside* the FLAC checkout on
branch ``localization-exp``. exp_14's cells are written to the NAS instead, so publishing
an arm means copying ten files across and registering a glob for them. Every step of that
fails quietly, which is what this module is for:

* **The glob decides which validator runs.** ``gen_model_comparison.py::is_exp14_row``
  claims any row whose pattern contains ``exp14_`` for the exp_14 *yaw* campaign, with a
  different protocol label and a validator that cannot parse these eval names (finding
  r3-3). Nothing this module emits -- directory, basename, label or pattern -- may carry
  that substring, and ``names.assert_no_forbidden_substring`` is applied to each.
* **A metrics JSON cannot prove it is this cell.** It records no seed and no dataset
  config, so a file left over from an earlier checkpoint, an earlier protocol or a reduced
  eval split reads as a finished result. The import therefore gates on the *pair*: the
  metrics record (checkpoint path, the digest the evaluator stamped in, all four
  conditioning flags) and its sibling prediction bundle (full 6,337-item split, the
  K-appropriate unseen config, same seed, same protocol, exactly-as-scored tensor).
* **A half-published arm is averaged without complaint.** So validation runs over all ten
  cells before a single byte is copied, the copy lands in a staging directory whose files
  are re-hashed before they are moved into place, and every digest is recorded beside the
  source path it came from in ``MANIFEST.sha256``.

No GPU, no network, and nothing in the destination checkout is committed or force-added
here: this module copies and prints, the analyst commits.

**Deferred, on purpose (plan §9 D9, codex D3 finding 7).** The plan also requires the
authoritative ``gen_model_comparison.py`` to be RUN end-to-end over a fixture import
directory, asserting five files per K, a numerically rendered row and the final protocol
label. That test belongs to the checkout that owns the generator (branch
``localization-exp``), not here, and the Planner schedules it before the first arm is
published. What this repository can prove -- and does, in
``src/tests/test_data_curve_import_cells.py`` -- is that the emitted string literal-parses
as one of the generator's own four-field ROWS entries and carries no forbidden substring.
"""
import argparse
import glob
import hashlib
import os
import shutil
import sys

from src.tools.data_curve import names

#: Inside the FLAC checkout, relative to its root. Deliberately not ``exp14_*``.
IMPORT_SUBDIR = os.path.join("outputs_FLAC", "data_curve_import")
#: What gen_model_comparison.py calls each arm's evaluation protocol. Mirrors the labels
#: already in its ROWS table ("fa eval" for frame-averaged arms, "vanilla eval" for stock),
#: so an exp_14 row reads in the same vocabulary as every row beside it.
ARM_PROTOCOL_LABEL = {"cyl": "fa eval", "van": "vanilla eval"}
MANIFEST_BASENAME = "MANIFEST.sha256"
EXIT_OK = names.EXIT_OK
EXIT_INPUT_ERROR = names.EXIT_INPUT_ERROR
EXIT_REFUSED = names.EXIT_BUNDLE_VIOLATION


def seed_glob(seeds=names.SEEDS):
    """``s4[2-6]`` for seeds 42-46 -- derived, with a guard, never typed."""
    low, high = min(seeds), max(seeds)
    if sorted(seeds) != list(range(low, high + 1)) or low // 10 != high // 10:
        raise ValueError(f"seeds {sorted(seeds)} are not one contiguous decade, so a "
                         "single character-class glob cannot name exactly them")
    return f"s{low // 10}[{low % 10}-{high % 10}]"


def row_spec(arm, tag, K, run=None, seeds=names.SEEDS):
    """The line to paste into ``gen_model_comparison.py``'s ROWS table for one cell block.

    ``(label, protocol, K, [glob])`` -- the four-field form every row there uses. The glob
    is relative to the FLAC checkout's root, which is what the generator resolves against.
    ``names.run_id`` does the arm/tag validation, so an unknown arm cannot reach the label.
    """
    run = run or names.run_id(arm, tag)
    if K not in names.K_VALUES:
        raise ValueError(f"unplanned K={K!r}; the experiment evaluates {names.K_VALUES}")
    pct = int(round(names.FRACTIONS[tag] * 100))
    label = f"data-curve {arm} f={pct}% @40k (exp_14 cyl-dinov3)"
    pattern = f"{IMPORT_SUBDIR}/{run}/*_K{K}_{seed_glob(seeds)}*.json"
    names.assert_no_forbidden_substring(label)
    names.assert_no_forbidden_substring(pattern)
    return f'("{label}", "{ARM_PROTOCOL_LABEL[arm]}", {K}, ["{pattern}"]),'


def _final_checkpoint(run_dir, step=names.MAX_STEPS):
    """The run's single step-``step`` checkpoint, or ``None`` with a reason."""
    hits = sorted(glob.glob(os.path.join(glob.escape(run_dir), f"*step={step}.ckpt")))
    if len(hits) == 1:
        return hits[0], None
    if not hits:
        return None, f"no step-{step} checkpoint in {run_dir}: this arm is not finished"
    return None, (f"{len(hits)} step-{step} checkpoints in {run_dir} -- which one produced "
                  "the cells beside them is not decidable here")


def _sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as fin:
        for chunk in iter(lambda: fin.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_cells(ckpt, arm, tag, expect_ckpt_sha256, seeds=names.SEEDS,
                   ks=names.K_VALUES, expect_n=None):
    """``(files, violations)`` -- every cell of one arm, gated as a metrics/bundle *pair*.

    ``expect_n`` overrides the 6,337-item contract for fixtures only; production callers
    leave it ``None`` so the split size comes from ``names.N_ITEMS_UNSEEN``.
    """
    n_items = names.N_ITEMS_UNSEEN if expect_n is None else expect_n
    cond_method = names.ARM_COND_METHOD[arm]
    files, violations = [], []
    for K in ks:
        for seed in seeds:
            where = f"K{K} s{seed}"
            metrics_path = names.metrics_json_path(ckpt, arm, tag, K, seed)
            bundle_path = names.predictions_pt_path(ckpt, arm, tag, K, seed)
            if not os.path.exists(metrics_path):
                violations.append(f"{where}: no metrics JSON at {metrics_path}")
                continue
            bad = names.check_metrics(metrics_path, ckpt, expect_ckpt_sha256, cond_method,
                                      names.FRAME_AVG_ANGLES, names.ROTATE_DEG,
                                      names.COND_AUTOCAST)
            if not os.path.exists(bundle_path):
                bad.append(f"no prediction bundle at {bundle_path}, so nothing proves this "
                           f"cell covered the full {n_items}-item unseen split")
            else:
                bad += names.check_bundle(bundle_path, n_items, seed, K, arm,
                                          expect_eval_name=names.eval_name(arm, tag, K, seed),
                                          expect_ckpt=ckpt,
                                          expect_ckpt_sha256=expect_ckpt_sha256)
            if bad:
                violations += [f"{where}: {line}" for line in bad]
                continue
            files.append({"source": metrics_path, "K": K, "seed": seed,
                          "sha256": _sha256(metrics_path)})
    return files, violations


def _identical(staging, dest_dir):
    """``(same, why)`` -- is what we would publish byte-for-byte what is already there?"""
    staged, published = sorted(os.listdir(staging)), sorted(os.listdir(dest_dir))
    if staged != published:
        differing = sorted(set(staged) ^ set(published))
        return False, f"its file list differs ({', '.join(differing)})"
    for basename in staged:
        if _sha256(os.path.join(staging, basename)) != \
                _sha256(os.path.join(dest_dir, basename)):
            return False, f"{basename} differs"
    return True, ""


def _write_manifest(staging, checkout, run, ckpt, ckpt_sha256, files):
    """``MANIFEST.sha256``: the sources above, the imported copies below.

    Written INTO the staging directory, so it travels with the files it describes and the
    destination never exists without it. The lower half is a plain ``sha256sum -c`` list
    rooted at the FLAC checkout; the upper half is commented out (``sha256sum`` skips ``#``
    lines) and names the NAS path each copy came from, which is the half a reader needs and
    ``sha256sum`` has no room for. Nothing in it is time-dependent, so an identical rerun
    produces identical bytes -- which is what makes the idempotent path checkable.
    """
    path = os.path.join(staging, MANIFEST_BASENAME)
    lines = [f"# exp_14 data-curve import -- {run}",
             "# written by src.tools.data_curve.import_cells (announcement 04, plan §9 D9)",
             f"# final checkpoint:        {ckpt}",
             f"# final checkpoint sha256: {ckpt_sha256}",
             "#", "# --- sources (sha256  NAS path) ---"]
    lines += [f"#{entry['sha256']}  {entry['source']}" for entry in files]
    lines += ["#", "# --- imported copies (sha256  path relative to the FLAC checkout) ---"]
    lines += [f"{entry['sha256']}  {os.path.relpath(entry['dest'], checkout)}"
              for entry in files]
    with open(path, "w") as fout:
        fout.write("\n".join(lines) + "\n")
    return path


def _stage_and_install(files, dest_dir, checkout, run, ckpt, ckpt_sha256):
    """``(violations, "new"|"identical")`` -- build the whole directory, then move it once.

    Installation is all-or-nothing, not just validation (codex D3 finding 3). The complete
    published directory -- ten cells AND their manifest -- is assembled in a sibling staging
    directory, every copied byte re-hashed there, and only then moved into place with a
    single ``os.rename``. A failure at any point therefore leaves no destination at all,
    rather than a partial one that the generator's glob would average without noticing.

    An existing destination is never merged into: byte-identical means the import already
    happened and this is an idempotent rerun; anything else is a refusal, because a stale
    file from an epoch-renamed earlier run matches the same glob as a fresh one.
    """
    parent = os.path.dirname(dest_dir)
    os.makedirs(parent, exist_ok=True)
    staging = os.path.join(parent, f".incoming-{os.path.basename(dest_dir)}-{os.getpid()}")
    shutil.rmtree(staging, ignore_errors=True)
    try:
        os.makedirs(staging)
        for entry in files:
            basename = names.assert_no_forbidden_substring(os.path.basename(entry["source"]))
            staged = os.path.join(staging, basename)
            shutil.copy2(entry["source"], staged)
            digest = _sha256(staged)
            if digest != entry["sha256"]:
                return [f"{basename}: the copy hashes to {digest}, not the source's "
                        f"{entry['sha256']} -- nothing was imported"], None
            entry["dest"] = os.path.join(dest_dir, basename)
        _write_manifest(staging, checkout, run, ckpt, ckpt_sha256, files)
        if os.path.exists(dest_dir):
            same, why = _identical(staging, dest_dir)
            if same:
                return [], "identical"
            return [f"{dest_dir} already exists and is not what this import would "
                    f"publish: {why}. Nothing was touched -- remove or move it by hand."], None
        os.rename(staging, dest_dir)
        return [], "new"
    finally:
        shutil.rmtree(staging, ignore_errors=True)


def import_run(nas_root, arm, tag, flac_checkout, expect_ckpt_sha256, seeds=names.SEEDS,
               ks=names.K_VALUES, expect_n=None, ckpt=None):
    """Copy one arm's ten metric JSONs into the FLAC checkout, or copy none of them.

    Returns ``(result, violations)``. ``violations`` non-empty means nothing was copied --
    a half-published arm would be globbed and averaged exactly like a complete one.
    ``ValueError`` is raised only for a caller bug (unknown arm/tag, a digest that is not a
    digest): that is not a verdict about the artifacts.
    """
    run = names.run_id(arm, tag)                    # validates the arm and the fraction
    # The one rule about what a checkpoint digest may be lives in names; re-stating it here
    # would create a second definition of "valid digest" that can drift from the launcher's.
    names._check_ckpt_sha256(expect_ckpt_sha256)
    run_dir = os.path.join(nas_root, run)
    dest_dir = os.path.join(flac_checkout, IMPORT_SUBDIR, run)
    names.assert_no_forbidden_substring(os.path.join(IMPORT_SUBDIR, run))
    result = {"run_id": run, "arm": arm, "fraction_tag": tag, "run_dir": run_dir,
              "dest_dir": dest_dir, "ckpt": ckpt, "ckpt_sha256": expect_ckpt_sha256,
              "files": [], "manifest": None, "installed": None,
              "row_specs": [row_spec(arm, tag, K, run) for K in ks]}
    # Discovery is unconditional (codex D3 finding 4). An override used to SKIP it, so an
    # internally consistent step-2500 checkpoint -- its own artifacts, its own digest, the
    # right protocol -- could be published as this arm's @40k result. The flag is now only
    # a cross-check: it must name the file discovery already found.
    discovered, why = _final_checkpoint(run_dir)
    if discovered is None:
        return result, [f"{run}: {why}"]
    if ckpt is not None and os.path.realpath(ckpt) != os.path.realpath(discovered):
        return result, [
            f"{run}: --ckpt-path {ckpt} is not this run's final checkpoint {discovered}; "
            f"only the single step-{names.MAX_STEPS} file may be published"]
    ckpt = result["ckpt"] = discovered
    on_disk = _sha256(ckpt) if os.path.exists(ckpt) else None
    if on_disk != expect_ckpt_sha256:
        return result, [f"{run}: {ckpt} hashes to {on_disk}, not the ckpt_sha256 "
                        f"{expect_ckpt_sha256} the launcher validated"]
    files, violations = validate_cells(ckpt, arm, tag, expect_ckpt_sha256, seeds, ks,
                                       expect_n)
    if violations:
        return result, violations
    try:
        violations, installed = _stage_and_install(files, dest_dir, flac_checkout, run,
                                                   ckpt, expect_ckpt_sha256)
    except OSError as err:
        return result, [f"{run}: the install failed and nothing was published "
                        f"({type(err).__name__}: {err})"]
    if violations:
        return result, violations
    result["files"] = files
    result["installed"] = installed
    result["manifest"] = os.path.join(dest_dir, MANIFEST_BASENAME)
    return result, []


def main(argv=None):
    """CLI: import one arm's cells and print the rows to add to gen_model_comparison.py."""
    parser = argparse.ArgumentParser(
        prog="python -m src.tools.data_curve.import_cells",
        description="Copy one exp_14 arm's ten metric JSONs into the FLAC checkout that "
                    "regenerates model_comparison.md, sha-verified, all-or-nothing.")
    parser.add_argument("--nas-root", required=True,
                        help="the directory holding the dc_<arm>_f<tag> run directories")
    parser.add_argument("--arm", required=True, choices=list(names.ARMS))
    parser.add_argument("--tag", required=True, choices=sorted(names.FRACTIONS))
    parser.add_argument("--flac-checkout", required=True,
                        help="the checkout that owns gen_model_comparison.py "
                             "(branch localization-exp)")
    parser.add_argument("--expect-ckpt-sha256", required=True,
                        help="the launch summary's final_ckpt_sha256 for this arm")
    parser.add_argument("--ckpt-path", default=None,
                        help="cross-check: must name the run's discovered step-40000 "
                             "checkpoint, which is published either way")
    args = parser.parse_args(argv)
    try:
        result, violations = import_run(args.nas_root, args.arm, args.tag,
                                        args.flac_checkout, args.expect_ckpt_sha256,
                                        ckpt=args.ckpt_path)
    except (OSError, ValueError) as err:
        print(f"import_cells: {type(err).__name__}: {err}", file=sys.stderr)
        return EXIT_INPUT_ERROR
    if violations:
        print(f"REFUSED: {result['run_id']} was not imported "
              f"({len(violations)} violations); nothing was copied", file=sys.stderr)
        for line in violations:
            print(f"  ! {line}", file=sys.stderr)
        return EXIT_REFUSED
    print(f"imported {len(result['files'])} cells of {result['run_id']} -> "
          f"{result['dest_dir']}")
    print(f"manifest: {result['manifest']} (staged, verified, installed in one move; "
          f"{result['installed']})")
    print("add these rows to worklog/worklog_yixun/gen_model_comparison.py::ROWS, "
          "force-add the JSONs + manifest, regenerate, commit and push:")
    for row in result["row_specs"]:
        print(f" {row}")
    return EXIT_OK


if __name__ == "__main__":     # pragma: no cover - exercised through main() in tests
    sys.exit(main())
