#!/usr/bin/env python3
"""gen_closing_page.py - renders fa_finetune_01_results.html (exp_09 closing page).
Presentation only; numbers transcribed from fa_finetune_results.md."""
import os

GATE = {"K=8": {"T60": ("8.4652", "0.0058", "-10.8", "SUPERIOR"), "C50": ("0.9582", "0.0010", "-3.2", "SUPERIOR"),
                "EDT": ("37.4968", "0.0813", "+3.7", "OUT"), "R@1": ("6.9243", "0.0701", "-1.1", "NONINF")},
        "K=1": {"T60": ("9.8271", "0.0612", "-2.0", "SUPERIOR"), "C50": ("1.0337", "0.0025", "-1.8", "SUPERIOR"),
                "EDT": ("40.8740", "0.3393", "+1.8", "NONINF"), "R@1": ("6.8581", "0.1108", "+0.1", "EQUIV")}}
REL = {"K=8": {"T60": "8.609", "C50": "0.9682", "EDT": "37.10", "R@1": "7.06"},
       "K=1": {"T60": "9.969", "C50": "1.0460", "EDT": "39.95", "R@1": "6.83"}}
SWEEP = [("0°", 8.668, 0.9924, 39.293, 6.502), ("90°", 8.667, 0.9925, 39.288, 6.502),
         ("180°", 8.667, 0.9924, 39.288, 6.486), ("270°", 8.668, 0.9925, 39.295, 6.502),
         ("45° (neg. control)", 9.466, 1.0674, 40.157, 5.192)]
TIER = {"SUPERIOR": "background:#0a5c2e;color:#fff", "EQUIV": "background:#1a4f7a;color:#fff",
        "NONINF": "background:#5a4a12;color:#fff", "OUT": "background:#6b1f1f;color:#fff"}

rows = "".join(
    f"<tr><td>{m}</td><td><b>{GATE['K=8'][m][0]} ± {GATE['K=8'][m][1]}</b></td><td>{REL['K=8'][m]}</td>"
    f"<td style='{TIER[GATE['K=8'][m][3]]}'>{GATE['K=8'][m][3]} ({GATE['K=8'][m][2]}σ)</td>"
    f"<td><b>{GATE['K=1'][m][0]} ± {GATE['K=1'][m][1]}</b></td><td>{REL['K=1'][m]}</td>"
    f"<td style='{TIER[GATE['K=1'][m][3]]}'>{GATE['K=1'][m][3]} ({GATE['K=1'][m][2]}σ)</td></tr>"
    for m in ["T60", "C50", "EDT", "R@1"])
sweep_rows = "".join(
    f"<tr><td>{a}</td><td>{t:.3f}</td><td>{c:.4f}</td><td>{e:.3f}</td><td>{r:.3f}</td></tr>"
    for a, t, c, e, r in SWEEP)

page = f"""<meta charset="utf-8"><title>exp_09 closing — equivariant FLAC at Table-1 level</title>
<style>body{{font-family:system-ui,sans-serif;max-width:1000px;margin:24px auto;padding:0 16px;background:#111;color:#eee}}
table{{border-collapse:collapse;margin:12px 0;width:100%}}td,th{{border:1px solid #444;padding:5px 9px;text-align:right;font-variant-numeric:tabular-nums}}
th{{background:#222}}td:first-child,th:first-child{{text-align:left}}
.hero{{background:#0a5c2e;color:#fff;padding:14px 18px;border-radius:8px}}
.warn{{background:#5a4a12;color:#fff;padding:10px 14px;border-radius:8px;margin:10px 0}}
.note{{background:#222;border-left:4px solid #1a4f7a;padding:8px 14px;margin:10px 0}}h2{{border-bottom:1px solid #333;padding-bottom:4px}}</style>
<h1>exp_09 fa_finetune — closing results</h1>
<div class="hero"><b>Exactly C₄-equivariant FLAC at released-Table-1-level quality.</b>
Checkpoint <code>exp09_Fw / epoch=20-step=95000</code> (fa fine-tune of the exp_07 anchor; evaluate with
<code>--cond-method fa_invariant</code>): rotations 0/90/180/270° identical to 3–4 decimals; vs released Table-1 (5 seeds, both K):
T60 &amp; C50 SUPERIOR at both K, R@1 matched, single concession +0.40 ms EDT at K=8. Formal tier: PARTIAL (FULL required 8/8).</div>
<h2>1 · G1 — C₄ rotation sweep (K=8, seed 42, ckpt 88750)</h2>
<table><tr><th>rotation</th><th>T60</th><th>C50</th><th>EDT</th><th>R@1</th></tr>{sweep_rows}</table>
<div class="note">Exact invariance across the C₄ orbit; the 45° control breaks by construction (fa is C₄-exact only).</div>
<h2>2 · Gate — Fw-95000 vs released Table-1 (5 eval seeds, full split, fa eval)</h2>
<table><tr><th>Metric</th><th>K=8 ours</th><th>K=8 released</th><th>verdict</th><th>K=1 ours</th><th>K=1 released</th><th>verdict</th></tr>{rows}</table>
<div class="warn"><b>Protocol-error record:</b> all fa-arm evals before 2026-07-30 ~19:50 ran with vanilla eval-time conditioning
(<code>--cond-method</code> never passed) — the interim "fine-tune damage" reading and the non-flat first sweep were artifacts of that
mismatch and are retired. Discovered via the pre-registered G1 sweep; full record in <code>fa_finetune_results.md</code> / <code>_worklog.md</code>.</div>
<h2>3 · Findings</h2>
<div class="note"><b>Warm vs reset:</b> Adam-moment reuse across the conditioning switch is immaterial (probe pick: warm, by a small margin). <b>Control:</b> continued-vanilla V oscillates in the anchor band; Fw's deltas sit inside it (G4 ΔΔ ≈ 0) — the fa cost at this lr is band-scale, concentrated in one EDT cell. <b>Program:</b> the exp_03–06 fine-tune-damage blocker does not reproduce from the strong warm-state anchor under the matched eval protocol.</div>
<p style="color:#888">Numbers first recorded in <code>fa_finetune_results.md</code>; page generated by <code>gen_closing_page.py</code>.</p>"""

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fa_finetune_01_results.html")
open(out, "w").write(page)
print("wrote", out, len(page), "bytes")
