"""
Generate the two context-ablation eval modules from AR_md_arbRIR_v0_eval_A.py
by TARGETED INJECTION — so the pose logic (pair_local/src_qrel/recs_qrel/
context_poses) is byte-identical to baseline_A_*_K1 and ONLY context_audio
differs. That identity is the entire validity argument for the control.

  zeroctx  : md['context_audio'] = zeros_like(...)            (audio channel off)
  wrongroom: md['context_audio'] = a different-ROOM RIR        (material mismatch)

Both keep Scheme-A poses. K=1 only.
"""
import os

SRC = "src/configs/dataset_configs/custom_metadata/AR_md_arbRIR_v0_eval_A.py"
DST_ZERO = "src/configs/dataset_configs/custom_metadata/AR_md_arbRIR_v0_eval_zeroctx.py"
DST_WR = "src/configs/dataset_configs/custom_metadata/AR_md_arbRIR_v0_eval_wrongroom.py"

base = open(SRC).read()

SCHEME_ANCHOR = '_SCHEME = "A"  # context_poses = src_qrel (s_i - r_q)'
POSES_ANCHOR = (
    "        # Baseline cross-attention contract — SCHEME A: s_i - r_q.\n"
    "        md['context_poses'] = src_qrel               # [N, 3]\n"
)
RESOLVER_ANCHOR = "    return path\n\n\ndef get_custom_metadata(info, audio):"

for a in (SCHEME_ANCHOR, POSES_ANCHOR, RESOLVER_ANCHOR):
    assert base.count(a) == 1, f"anchor not unique/found, eval_A drifted: {a!r}"

HEADER = '''"""
AUTO-GENERATED by tools/gen_context_ablation_modules.py — DO NOT EDIT BY HAND.
Context-ablation control ({variant}) for the advisor's "context RIR = material
proxy" hypothesis. Cloned from AR_md_arbRIR_v0_eval_A.py with the pose logic
left BYTE-IDENTICAL; only md['context_audio'] is overridden ({what}). Scheme-A
poses, K=1 only. Differs from baseline_A_*_K1 in exactly one tensor.
"""'''

# ---- zeroctx ----
z = base
z = z[z.index('"""', z.index('"""') + 3) + 3:]  # drop original docstring
z = HEADER.format(variant="zeroctx", what="zeros") + z
z = z.replace(SCHEME_ANCHOR, '_SCHEME = "zeroctx"  # Scheme-A poses; context audio zeroed')
z = z.replace(
    POSES_ANCHOR,
    POSES_ANCHOR
    + "        # === ZEROCTX OVERRIDE: ablate the context audio channel ===\n"
    "        md['context_audio'] = torch.zeros_like(md['context_audio'])\n",
)
open(DST_ZERO, "w").write(z)
print(f"[ok] wrote {DST_ZERO}")

# ---- wrongroom ----
w = base
w = w[w.index('"""', w.index('"""') + 3) + 3:]
w = HEADER.format(variant="wrongroom", what="a different-room RIR") + w
w = w.replace(SCHEME_ANCHOR, '_SCHEME = "wrongroom"  # Scheme-A poses; context audio from a different room')

WR_HELPERS = '''    return path


_WRONGROOM_CACHE = {}


def _get_wrongroom(p):
    m = _WRONGROOM_CACHE.get(p)
    if m is None:
        with open(p) as f:
            m = json.load(f)
        _WRONGROOM_CACHE[p] = m
    return m


def _resolve_wrongroom_path(info):
    """Fail-loud seen/unseen resolver for the wrong-room donor manifest."""
    jfp = info.get('json_file_path') or ''
    base = os.path.basename(jfp)
    if base == 'unseen_eval.json':
        split = 'unseen'
    elif base == 'seen_eval.json':
        split = 'seen'
    else:
        raise RuntimeError(
            f"[arbRIR_v0_eval_wrongroom] cannot resolve split from "
            f"json_file_path={jfp!r}")
    path = f"data/AR/arbRIR_v0_eval_wrongroom_{split}.json"
    if not os.path.exists(path):
        raise RuntimeError(
            f"[arbRIR_v0_eval_wrongroom] donor manifest not found: {path}. "
            f"Run tools/build_wrongroom_donor_manifest.py")
    return path


def get_custom_metadata(info, audio):'''
w = w.replace(RESOLVER_ANCHOR, WR_HELPERS)

WR_OVERRIDE = (
    POSES_ANCHOR
    + "        # === WRONGROOM OVERRIDE: swap context AUDIO for a different-room\n"
    "        #     RIR; the poses above are UNCHANGED (identical to base_A K=1). ===\n"
    '        if num_ref != 1:\n'
    '            raise RuntimeError(f"[arbRIR_v0_eval_wrongroom] K=1 only, got {num_ref}")\n'
    "        _wr = _get_wrongroom(_resolve_wrongroom_path(info))\n"
    '        _wk = f"{scene_name}/{scene_id}/{filename}"\n'
    "        if _wk not in _wr:\n"
    '            raise KeyError(f"[arbRIR_v0_eval_wrongroom] {_wk!r} not in donor manifest")\n'
    "        _ds, _did, _dwav = _wr[_wk]\n"
    "        _ir_root = os.path.dirname(os.path.dirname(os.path.dirname(full_audio_path)))\n"
    "        _dfp = os.path.join(_ir_root, _ds, _did, _dwav)\n"
    "        _dw, _dr = torchaudio.load(_dfp)\n"
    '        assert _dr == 22050, "IR sampling rate must be 22050!"\n'
    "        if _dw.shape[1] < max_len_cond:\n"
    "            _dw = torch.cat([_dw, torch.zeros(_dw.shape[0], max_len_cond - _dw.shape[1])], dim=1)\n"
    "        else:\n"
    "            _dw = _dw[:, :max_len_cond]\n"
    "        md['context_audio'] = _dw.unsqueeze(0)  # [1,1,max_len] from a DIFFERENT room\n"
)
w = w.replace(POSES_ANCHOR, WR_OVERRIDE)
open(DST_WR, "w").write(w)
print(f"[ok] wrote {DST_WR}")

# byte sanity: both still import-compile
import py_compile
for f in (DST_ZERO, DST_WR):
    py_compile.compile(f, doraise=True)
    print(f"[ok] py_compile {f}")
